version: '3'
services:
  django:
    build: .
    ports:
      - "8500:8000"  # Порт хоста:порт контейнера Django
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "8000:5432"  # Порт хоста:порт контейнера PostgreSQL
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clothing_store