# Generated by Django 4.2.2 on 2023-06-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
