# Generated by Django 4.2.2 on 2023-06-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo', '0005_product_model_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
