# Generated by Django 4.2.2 on 2023-06-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo', '0007_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
